language: node_js
node_js:
  - "6"
services:
  - mongodb
before_script:
    - mongoimport --db selene --collection images --drop test/db/db.images.test.json
    - mongoimport --db selene --collection image_angles --drop test/db/db.image_angles.test.json
